name: Dummy Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Grab the code
        uses: actions/checkout@v5
      - name: List the files 
        run: